### ISSUE TITLE
Converting BigInteger.ZERO to byte array returns empty array

### ISSUE THREAD

**Issue by lucebac** [tls-attacker/ModifiableVariable#54]
Currently, ArrayConvert.bigIntegerToByteArray returns an empty byte array when called with `(BigInteger.ZERO, XX, true)`. That is, because the following if clause removes the one zero byte that represents the BigInteger.ZERO:

https://github.com/tls-attacker/ModifiableVariable/blob/f60c1eb09520ac6b5716700c196b4814bbd1b6ee/src/main/java/de/rub/nds/modifiablevariable/util/ArrayConverter.java#L289-L294

To me, that feels like a bug because even if BigInteger.ZERO could generally have a sign, not returning the actual `byte[] {0}` that represents the ZERO integer is definitely wrong.

**Comment by lucebac** [comment]
Reproduce with `KeyShareCalculatorTest#crashTest`

**Comment by ic0ns** [comment]
in TLS BigIntegers are generally not encoded with sign bits. If you want a zero padded big integer there is actually a function for that

**Comment by lucebac** [comment]
That means that if I put in a BigInteger.ZERO into this function I cannot expect to get a `new byte[] {0}` as a result? Sounds odd to me tbh.

But if that is indeed how this is supposed to work, then some code in TLS-Attacker has to be changed because empty arrays are not expected as a return value on at least one occasion.

**Comment by ic0ns** [comment]
well why wouldnt you get new byte[2]; out of it, or new byte[3] ?

**Comment by lucebac** [comment]
I don't know, I just reported my observations here: BigInteger.ZERO got converted to `new byte[1] {0}`, the referenced code path removed the single zero byte b/c it thinks that's a sign byte which ultimately results in returning a zero-length array to the caller instead of the single zero byte which I, personally, would expect to be returned when I put in a zero to this function.

**Comment by lucebac** [comment]
A small addition that maybe explains my point a little bit more: for me this feels like the classical case of `null != 0`. If the function is passed a `null` BigInteger I'm perfectly fine if the return value is `new byte[0]` to reflect that. On the other hand, if I pass an explicit zero, I would like to have the zero returned as `new byte[1] {0}` to reflect that I passed the zero and not an "empty" BigInteger.

Still, this is personal preference here.

**Comment by ic0ns** [comment]
![raceison](https://user-images.githubusercontent.com/10171186/110135464-d843f780-7dce-11eb-9c11-b2d2e0c3e0c4.png)

**Comment by lucebac** [comment]
Closing, because works as intented then.
